Repository SIDETEAM001/side-backend, pull requests merged in 2024-01, with the labels that each got.

#26 위치 저장 / 조회 기능
  build.gradle
  src/main/java/com/sideteam/groupsaver/domain/location/Region1TypeAttributeConverter.java
  src/main/java/com/sideteam/groupsaver/domain/location/controller/LocationController.java
  src/main/java/com/sideteam/groupsaver/domain/location/domain/Location.java
  src/main/java/com/sideteam/groupsaver/domain/location/domain/LocationCoordinate.java
  src/main/java/com/sideteam/groupsaver/domain/location/domain/Region1Type.java
  src/main/java/com/sideteam/groupsaver/domain/location/dto/kakao/KakaoCoordinate2RegionResponse.java
  src/main/java/com/sideteam/groupsaver/domain/location/dto/kakao/KakaoLocationResponse.java
  src/main/java/com/sideteam/groupsaver/domain/location/dto/response/CoordinateDistanceResponse.java
  src/main/java/com/sideteam/groupsaver/domain/location/dto/response/LocationResponse.java
  src/main/java/com/sideteam/groupsaver/domain/location/repository/LocationRepository.java
  src/main/java/com/sideteam/groupsaver/domain/location/service/LocationClient.java
  src/main/java/com/sideteam/groupsaver/domain/location/service/LocationKakaoClient.java
  src/main/java/com/sideteam/groupsaver/domain/location/service/LocationService.java
  src/main/java/com/sideteam/groupsaver/domain/location/service/LocationUtils.java
  src/main/java/com/sideteam/groupsaver/global/config/WebClientConfig.java
  src/main/java/com/sideteam/groupsaver/global/util/converter/AbstractEnumAttributeConverter.java
  src/main/java/com/sideteam/groupsaver/global/util/converter/EnumValue.java
  src/main/java/com/sideteam/groupsaver/global/util/converter/LegacyEnumValueConvertUtils.java
  src/main/resources/application.yml
  src/test/java/com/sideteam/groupsaver/domain/location/service/LocationKakaoClientTest.java
  src/test/java/com/sideteam/groupsaver/domain/location/service/LocationSplitter.java
  src/test/java/com/sideteam/groupsaver/domain/location/service/LocationUtilsTest.java
  src/test/resources/location/search-by-address-response.csv
  src/test/resources/location/search-by-coordinate-response.csv
Labels: Feat

#12 AWS S3를 사용한 이미지 업로드 기능 구현
  build.gradle
  src/main/java/com/sideteam/groupsaver/domain/file/api/FileController.java
  src/main/java/com/sideteam/groupsaver/domain/file/domain/ResourceFile.java
  src/main/java/com/sideteam/groupsaver/domain/file/dto/FileUrlDto.java
  src/main/java/com/sideteam/groupsaver/domain/file/repository/ResourceFileRepository.java
  src/main/java/com/sideteam/groupsaver/global/exception/file/FileErrorCode.java
  src/main/java/com/sideteam/groupsaver/global/exception/file/FileException.java
  src/main/java/com/sideteam/groupsaver/infra/file/AwsS3Config.java
  src/main/java/com/sideteam/groupsaver/infra/file/FileService.java
  src/main/java/com/sideteam/groupsaver/infra/file/FileServiceS3Impl.java
  src/main/resources/application.yml
Labels: Feat

#39 Swagger 적용
  build.gradle
  src/main/java/com/sideteam/groupsaver/domain/auth/controller/AuthController.java
  src/main/java/com/sideteam/groupsaver/domain/auth/service/AuthTokenService.java
  src/main/java/com/sideteam/groupsaver/domain/auth/service/OAuthLoginService.java
  src/main/java/com/sideteam/groupsaver/domain/club/controller/ClubController.java
  src/main/java/com/sideteam/groupsaver/domain/club/controller/ClubInfoController.java
  src/main/java/com/sideteam/groupsaver/domain/club/controller/ClubMemberController.java
  src/main/java/com/sideteam/groupsaver/domain/club/dto/request/ClubRequest.java
  src/main/java/com/sideteam/groupsaver/domain/club_schedule/dto/request/ClubScheduleRequest.java
  src/main/java/com/sideteam/groupsaver/domain/location/dto/request/LocationInfoRequest.java
  src/main/java/com/sideteam/groupsaver/domain/mypage/dto/request/MyInfoUpdateRequest.java
  src/main/java/com/sideteam/groupsaver/global/auth/TokenFacade.java
  src/main/java/com/sideteam/groupsaver/global/config/security/SecurityConfig.java
  src/main/java/com/sideteam/groupsaver/global/config/swagger/DisableSwaggerSecurity.java
  src/main/java/com/sideteam/groupsaver/global/config/swagger/SwaggerConfig.java
  src/main/java/com/sideteam/groupsaver/global/exception/ApiErrorCode.java
  src/main/java/com/sideteam/groupsaver/global/exception/ApiErrorResponse.java
  src/main/java/com/sideteam/groupsaver/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sideteam/groupsaver/global/resolver/member_info/MemberIdParam.java
  src/main/java/com/sideteam/groupsaver/global/util/ProjectTimeFormat.java
  src/main/resources/application.yml
Labels: Feat

#43 회원가입에 필요한 데이터 추가 & 랜덤 닉네임 생성기
  src/main/java/com/sideteam/groupsaver/domain/auth/dto/request/SignupRequest.java
  src/main/java/com/sideteam/groupsaver/domain/auth/service/AuthSignupService.java
  src/main/java/com/sideteam/groupsaver/domain/member/domain/Member.java
  src/main/java/com/sideteam/groupsaver/domain/member/repository/MemberRepository.java
  src/main/java/com/sideteam/groupsaver/domain/randomNickname/controller/NicknameController.java
  src/main/java/com/sideteam/groupsaver/domain/randomNickname/domain/NicknameAD.java
  src/main/java/com/sideteam/groupsaver/domain/randomNickname/domain/NicknameNoun.java
  src/main/java/com/sideteam/groupsaver/domain/randomNickname/dto/NicknameResponseDto.java
  src/main/java/com/sideteam/groupsaver/domain/randomNickname/repository/RandomNicknameADResource.java
  src/main/java/com/sideteam/groupsaver/domain/randomNickname/repository/RandomNicknameNounResource.java
  src/main/java/com/sideteam/groupsaver/domain/randomNickname/service/NicknameService.java
  src/main/java/com/sideteam/groupsaver/global/config/security/SecurityConfig.java
  src/main/resources/dml.sql
Labels: Feat

#47 CI/CD를 위한 github actions 추가
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/dev-cd.yml
  .github/workflows/dev-ci.yml
  .github/workflows/prod-cd.yml
  .github/workflows/prod-ci.yml
  build.gradle
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/resource-app.yml
  src/main/resources/resource-infra.yml
  src/test/java/com/sideteam/groupsaver/GroupSaverApplicationTests.java
  src/test/java/com/sideteam/groupsaver/config/IntegrationSpringBootTest.java
  src/test/java/com/sideteam/groupsaver/config/TestRedisConfiguration.java
  src/test/java/com/sideteam/groupsaver/integration/auth/AuthIntegrationTest.java
Labels: Setting

#50 모임 채팅
  build.gradle
  src/main/java/com/sideteam/groupsaver/domain/chat/Chat.java
  src/main/java/com/sideteam/groupsaver/domain/chat/ChatController.java
  src/main/java/com/sideteam/groupsaver/domain/chat/ChatRepository.java
  src/main/java/com/sideteam/groupsaver/domain/chat/ChatService.java
  src/main/java/com/sideteam/groupsaver/domain/chat/dto/MessageType.java
  src/main/java/com/sideteam/groupsaver/domain/chat/dto/WebSocketIdentity.java
  src/main/java/com/sideteam/groupsaver/domain/chat/dto/request/ChatRequest.java
  src/main/java/com/sideteam/groupsaver/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/sideteam/groupsaver/domain/club/repository/ClubMemberRepository.java
  src/main/java/com/sideteam/groupsaver/domain/common/BaseTimeEntity.java
  src/main/java/com/sideteam/groupsaver/global/auth/jwt/JwtTokenProvider.java
  src/main/java/com/sideteam/groupsaver/global/config/security/SecurityConfig.java
  src/main/java/com/sideteam/groupsaver/global/exception/websocket/WebSocketErrorCode.java
  src/main/java/com/sideteam/groupsaver/global/websocket/WebSocketAuthInterceptor.java
  src/main/java/com/sideteam/groupsaver/global/websocket/WebSocketConfig.java
  src/main/java/com/sideteam/groupsaver/global/websocket/WebSocketUtils.java
Labels: Feat

#46 이메일 찾기 및 비밀번호 변경 기능
  build.gradle
  src/main/java/com/sideteam/groupsaver/domain/email/controller/EmailController.java
  src/main/java/com/sideteam/groupsaver/domain/email/controller/EmailPhoneController.java
  src/main/java/com/sideteam/groupsaver/domain/email/controller/PasswordController.java
  src/main/java/com/sideteam/groupsaver/domain/email/controller/PasswordPhoneController.java
  src/main/java/com/sideteam/groupsaver/domain/email/domain/EmailMessage.java
  src/main/java/com/sideteam/groupsaver/domain/email/dto/request/ChangePwPhoneRequest.java
  src/main/java/com/sideteam/groupsaver/domain/email/dto/request/ChangePwRequest.java
  src/main/java/com/sideteam/groupsaver/domain/email/dto/request/CheckEmailCodeRequest.java
  src/main/java/com/sideteam/groupsaver/domain/email/dto/request/CheckPwEmailCodeRequest.java
  src/main/java/com/sideteam/groupsaver/domain/email/dto/request/EmailRequest.java
  src/main/java/com/sideteam/groupsaver/domain/email/dto/request/FindEmailByPhoneRequest.java
  src/main/java/com/sideteam/groupsaver/domain/email/dto/request/PwRequest.java
  src/main/java/com/sideteam/groupsaver/domain/email/dto/response/FindEmailResponse.java
  src/main/java/com/sideteam/groupsaver/domain/email/repository/EmailRepository.java
  src/main/java/com/sideteam/groupsaver/domain/email/service/EmailPhoneService.java
  src/main/java/com/sideteam/groupsaver/domain/email/service/EmailService.java
  src/main/java/com/sideteam/groupsaver/domain/email/service/PasswordPhoneService.java
  src/main/java/com/sideteam/groupsaver/domain/email/service/PasswordService.java
  src/main/java/com/sideteam/groupsaver/domain/member/domain/Member.java
  src/main/java/com/sideteam/groupsaver/domain/member/repository/MemberRepository.java
  src/main/java/com/sideteam/groupsaver/global/config/security/SecurityConfig.java
  src/main/java/com/sideteam/groupsaver/global/emailAuthCode/AuthCode.java
  src/main/java/com/sideteam/groupsaver/global/emailAuthCode/AuthCodeRepository.java
  src/main/java/com/sideteam/groupsaver/global/emailAuthCode/AuthCodeService.java
  src/main/java/com/sideteam/groupsaver/global/exception/auth/AuthErrorCode.java
  src/main/java/com/sideteam/groupsaver/global/exception/member/MemberErrorCode.java
  src/main/java/com/sideteam/groupsaver/global/util/ProjectTimeFormat.java
  src/main/resources/application.yml
Labels: Feat

#31 FcmToken 저장 및 알림 기능 개발
  build.gradle
  src/main/java/com/sideteam/groupsaver/domain/firebase/controller/FcmTokenController.java
  src/main/java/com/sideteam/groupsaver/domain/firebase/domain/FcmToken.java
  src/main/java/com/sideteam/groupsaver/domain/firebase/dto/CreateFcmTokenDto.java
  src/main/java/com/sideteam/groupsaver/domain/firebase/dto/DeleteFcmTokenRequest.java
  src/main/java/com/sideteam/groupsaver/domain/firebase/repository/FcmTokenRepository.java
  src/main/java/com/sideteam/groupsaver/domain/firebase/service/FcmTokenService.java
  src/main/java/com/sideteam/groupsaver/global/auth/firebase/FcmConfig.java
  src/main/java/com/sideteam/groupsaver/global/config/security/SecurityConfig.java
  src/test/java/com/sideteam/groupsaver/domain/firebase/service/FcmTokenServiceTest.java
Labels: Feat

#55 CICD 수정 및 테스트 코드 수정
  .github/workflows/dev-cd.yml
  .github/workflows/dev-ci.yml
  .github/workflows/prod-cd.yml
  .github/workflows/prod-ci.yml
  src/main/java/com/sideteam/groupsaver/domain/firebase/service/FcmTokenService.java
  src/main/java/com/sideteam/groupsaver/global/auth/firebase/FcmConfig.java
  src/main/java/com/sideteam/groupsaver/global/config/firebase/FcmConfig.java
  src/main/java/com/sideteam/groupsaver/global/exception/firebase/FirebaseErrorCode.java
  src/main/resources/resource-infra.yml
  src/test/java/com/sideteam/groupsaver/domain/firebase/service/FcmTokenServiceTest.java
Labels: Fix
