Repository SIDETEAM001/side-backend, pull requests merged in 2024-02, with the labels that each got.

#51 클럽 및 유저 신고 기능
  build.gradle
  src/main/java/com/sideteam/groupsaver/domain/club/domain/Club.java
  src/main/java/com/sideteam/groupsaver/domain/club/repository/ClubRepository.java
  src/main/java/com/sideteam/groupsaver/domain/member/domain/Member.java
  src/main/java/com/sideteam/groupsaver/domain/member/domain/MemberActive.java
  src/main/java/com/sideteam/groupsaver/domain/member/repository/MemberRepository.java
  src/main/java/com/sideteam/groupsaver/domain/report/controller/ReportClubController.java
  src/main/java/com/sideteam/groupsaver/domain/report/controller/ReportUserController.java
  src/main/java/com/sideteam/groupsaver/domain/report/domain/ReportClub.java
  src/main/java/com/sideteam/groupsaver/domain/report/domain/ReportClubCategory.java
  src/main/java/com/sideteam/groupsaver/domain/report/domain/ReportUser.java
  src/main/java/com/sideteam/groupsaver/domain/report/domain/ReportUserCategory.java
  src/main/java/com/sideteam/groupsaver/domain/report/dto/ReportClubRequest.java
  src/main/java/com/sideteam/groupsaver/domain/report/dto/ReportUserRequest.java
  src/main/java/com/sideteam/groupsaver/domain/report/repository/ReportClubRepository.java
  src/main/java/com/sideteam/groupsaver/domain/report/repository/ReportUserRepository.java
  src/main/java/com/sideteam/groupsaver/domain/report/service/ReportClubService.java
  src/main/java/com/sideteam/groupsaver/domain/report/service/ReportUserService.java
  src/main/java/com/sideteam/groupsaver/domain/slack/SlackService.java
  src/main/java/com/sideteam/groupsaver/global/exception/club/ClubErrorCode.java
  src/main/resources/resource-infra.yml
Labels: Feat

#60 사용자가 선택한 카테고리별 모임 추천
  src/main/java/com/sideteam/groupsaver/domain/club/controller/ClubRecommendController.java
  src/main/java/com/sideteam/groupsaver/domain/club/domain/Club.java
  src/main/java/com/sideteam/groupsaver/domain/club/repository/ClubRepository.java
  src/main/java/com/sideteam/groupsaver/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/com/sideteam/groupsaver/domain/club/repository/ClubRepositoryCustomImpl.java
  src/main/java/com/sideteam/groupsaver/domain/club/service/ClubRecommendService.java
  src/main/java/com/sideteam/groupsaver/domain/join/repository/WantClubCategoryRepository.java
  src/main/java/com/sideteam/groupsaver/domain/location/domain/LocationCoordinate.java
  src/main/java/com/sideteam/groupsaver/global/config/SchedulingConfig.java
  src/main/java/com/sideteam/groupsaver/global/util/ProjectTimeFormat.java
  src/main/java/com/sideteam/groupsaver/global/util/QueryUtils.java
  src/main/java/com/sideteam/groupsaver/global/util/RandomUtils.java
  src/main/java/com/sideteam/groupsaver/global/util/SpatialExpressions.java
Labels: Feat

#66 카카오맵 지도 API 오류 fix
  src/main/java/com/sideteam/groupsaver/domain/common/BaseTimeEntity.java
  src/main/java/com/sideteam/groupsaver/domain/location/domain/Location.java
  src/main/java/com/sideteam/groupsaver/domain/location/domain/Region1Type.java
  src/main/java/com/sideteam/groupsaver/domain/location/dto/LocationData.java
  src/main/java/com/sideteam/groupsaver/domain/location/dto/kakao/KakaoCoordinate2RegionResponse.java
  src/main/java/com/sideteam/groupsaver/domain/location/dto/kakao/KakaoLocationResponse.java
  src/main/java/com/sideteam/groupsaver/domain/location/repository/LocationCustomRepository.java
  src/main/java/com/sideteam/groupsaver/domain/location/repository/LocationCustomRepositoryImpl.java
  src/main/java/com/sideteam/groupsaver/domain/location/repository/LocationRepository.java
  src/main/java/com/sideteam/groupsaver/domain/location/service/LocationKakaoClient.java
  src/main/java/com/sideteam/groupsaver/global/database/MySqlFunctionContributor.java
  src/main/java/com/sideteam/groupsaver/global/database/SqlFunction.java
  src/main/java/com/sideteam/groupsaver/global/database/SqlFunctionPropertyLoader.java
  src/main/java/com/sideteam/groupsaver/global/exception/location/LocationErrorCode.java
  src/main/java/com/sideteam/groupsaver/global/util/ProjectTimeFormat.java
  src/main/java/com/sideteam/groupsaver/global/util/QueryUtils.java
  src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
  src/main/resources/application.yml
  src/main/resources/resource-app.yml
  src/test/java/com/sideteam/groupsaver/domain/location/service/LocationKakaoClientTest.java
  src/test/resources/location/search-by-address-response.csv
  src/test/resources/location/search-by-coordinate-response.csv
Labels: Bug, Fix

#68 클럽 생성 요청시 문자열을 Enum으로 변환
  src/main/java/com/sideteam/groupsaver/domain/category/domain/ClubCategoryMajor.java
  src/main/java/com/sideteam/groupsaver/domain/category/domain/ClubCategorySub.java
  src/main/java/com/sideteam/groupsaver/domain/category/domain/JobMajor.java
  src/main/java/com/sideteam/groupsaver/domain/club/domain/ClubActivityType.java
  src/main/java/com/sideteam/groupsaver/domain/club/domain/ClubType.java
  src/main/java/com/sideteam/groupsaver/domain/club/dto/request/ClubRequest.java
  src/main/java/com/sideteam/groupsaver/domain/club/dto/response/ClubInfoResponse.java
  src/main/java/com/sideteam/groupsaver/global/exception/category/CategoryErrorCode.java
Labels: Refactor

#70 회원 계정 관련 API 구현
  src/main/java/com/sideteam/groupsaver/domain/auth/dto/request/SignupRequest.java
  src/main/java/com/sideteam/groupsaver/domain/auth/dto/response/SignupResult.java
  src/main/java/com/sideteam/groupsaver/domain/auth/service/AuthSignupService.java
  src/main/java/com/sideteam/groupsaver/domain/auth/service/OAuthLoginService.java
  src/main/java/com/sideteam/groupsaver/domain/club/controller/ClubBookmarkController.java
  src/main/java/com/sideteam/groupsaver/domain/club/domain/Club.java
  src/main/java/com/sideteam/groupsaver/domain/club/domain/ClubMember.java
  src/main/java/com/sideteam/groupsaver/domain/club/dto/response/ClubSimpleInfoDto.java
  src/main/java/com/sideteam/groupsaver/domain/club/repository/ClubMemberRepository.java
  src/main/java/com/sideteam/groupsaver/domain/club/service/ClubBookmarkService.java
  src/main/java/com/sideteam/groupsaver/domain/email/service/PasswordPhoneService.java
  src/main/java/com/sideteam/groupsaver/domain/email/service/PasswordService.java
  src/main/java/com/sideteam/groupsaver/domain/join/domain/ClubBookmark.java
  src/main/java/com/sideteam/groupsaver/domain/join/repository/ClubBookmarkRepository.java
  src/main/java/com/sideteam/groupsaver/domain/join/repository/WantClubCategoryRepository.java
  src/main/java/com/sideteam/groupsaver/domain/member/MemberConstants.java
  src/main/java/com/sideteam/groupsaver/domain/member/controller/MemberProfileController.java
  src/main/java/com/sideteam/groupsaver/domain/member/controller/MemberStatusController.java
  src/main/java/com/sideteam/groupsaver/domain/member/controller/MyClubController.java
  src/main/java/com/sideteam/groupsaver/domain/member/domain/Member.java
  src/main/java/com/sideteam/groupsaver/domain/member/domain/MemberAgreeTerms.java
  src/main/java/com/sideteam/groupsaver/domain/member/domain/MemberGender.java
  src/main/java/com/sideteam/groupsaver/domain/member/domain/MemberRole.java
  src/main/java/com/sideteam/groupsaver/domain/member/domain/MemberRoleConverter.java
  src/main/java/com/sideteam/groupsaver/domain/member/dto/request/MemberProfileUpdateRequest.java
  src/main/java/com/sideteam/groupsaver/domain/member/dto/response/MemberProfileResponse.java
  src/main/java/com/sideteam/groupsaver/domain/member/dto/response/MyBookmarkClubResponse.java
  src/main/java/com/sideteam/groupsaver/domain/member/dto/response/MyClubResponse.java
  src/main/java/com/sideteam/groupsaver/domain/member/dto/response/MyProfileResponse.java
  src/main/java/com/sideteam/groupsaver/domain/member/repository/MemberRepository.java
  src/main/java/com/sideteam/groupsaver/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/sideteam/groupsaver/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/sideteam/groupsaver/domain/member/service/MemberClubService.java
  src/main/java/com/sideteam/groupsaver/domain/member/service/MemberProfileService.java
  src/main/java/com/sideteam/groupsaver/domain/member/service/MemberUpdateService.java
  src/main/java/com/sideteam/groupsaver/domain/mypage/controller/MyPageController.java
  src/main/java/com/sideteam/groupsaver/domain/mypage/dto/request/MyInfoUpdateRequest.java
  src/main/java/com/sideteam/groupsaver/domain/mypage/dto/response/ClubFindResponse.java
  src/main/java/com/sideteam/groupsaver/domain/mypage/dto/response/MyInfoFindResponse.java
  src/main/java/com/sideteam/groupsaver/domain/mypage/service/MyPageService.java
  src/main/java/com/sideteam/groupsaver/global/auth/AuthConstants.java
  src/main/java/com/sideteam/groupsaver/global/auth/userdetails/CustomUserDetails.java
  src/main/java/com/sideteam/groupsaver/global/config/security/SecurityAuthConfig.java
  src/main/java/com/sideteam/groupsaver/global/util/AuthorityChecker.java
  src/test/java/com/sideteam/groupsaver/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/sideteam/groupsaver/integration/auth/AuthIntegrationTest.java
  src/test/java/com/sideteam/groupsaver/utils/provider/ClubProvider.java
  src/test/java/com/sideteam/groupsaver/utils/provider/MemberProvider.java
Labels: Feat

#71 온라인 모임에 기본 주소가 저장되는 사항 수정
  build.gradle
  src/main/java/com/sideteam/groupsaver/domain/category/domain/ClubCategory.java
  src/main/java/com/sideteam/groupsaver/domain/category/domain/ClubCategoryMajor.java
  src/main/java/com/sideteam/groupsaver/domain/category/domain/ClubCategorySub.java
  src/main/java/com/sideteam/groupsaver/domain/category/domain/JobMajor.java
  src/main/java/com/sideteam/groupsaver/domain/club/domain/Club.java
  src/main/java/com/sideteam/groupsaver/domain/club/domain/ClubActivityType.java
  src/main/java/com/sideteam/groupsaver/domain/club/domain/ClubMemberRole.java
  src/main/java/com/sideteam/groupsaver/domain/club/domain/ClubType.java
  src/main/java/com/sideteam/groupsaver/domain/club/dto/request/ClubRequest.java
  src/main/java/com/sideteam/groupsaver/domain/club/dto/response/ClubInfoResponse.java
  src/main/java/com/sideteam/groupsaver/domain/club/repository/ClubMemberRepository.java
  src/main/java/com/sideteam/groupsaver/domain/club/repository/ClubMemberRepositoryCustom.java
  src/main/java/com/sideteam/groupsaver/domain/club/repository/ClubMemberRepositoryCustomImpl.java
  src/main/java/com/sideteam/groupsaver/domain/club/repository/ClubRepositoryCustomImpl.java
  src/main/java/com/sideteam/groupsaver/domain/club/service/ClubMemberService.java
  src/main/java/com/sideteam/groupsaver/domain/club/service/ClubService.java
  src/main/java/com/sideteam/groupsaver/domain/join/domain/ClubBookmark.java
  src/main/java/com/sideteam/groupsaver/domain/join/domain/WantClubCategory.java
  src/main/java/com/sideteam/groupsaver/domain/location/converter/LocationInfoDeserializer.java
  src/main/java/com/sideteam/groupsaver/domain/location/domain/Region1Type.java
  src/main/java/com/sideteam/groupsaver/domain/location/dto/request/LocationInfoRequest.java
  src/main/java/com/sideteam/groupsaver/domain/location/dto/response/LocationInfoResponse.java
  src/main/java/com/sideteam/groupsaver/global/config/RedisConfig.java
  src/main/java/com/sideteam/groupsaver/global/exception/category/CategoryErrorCode.java
  src/test/java/com/sideteam/groupsaver/GroupSaverApplicationTests.java
  src/test/java/com/sideteam/groupsaver/config/TestRedisConfiguration.java
  src/test/java/com/sideteam/groupsaver/domain/club/repository/ClubMemberRepositoryTest.java
  src/test/java/com/sideteam/groupsaver/domain/firebase/service/FcmTokenServiceTest.java
  src/test/java/com/sideteam/groupsaver/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/sideteam/groupsaver/integration/auth/AuthIntegrationTest.java
  src/test/java/com/sideteam/groupsaver/utils/context/DataJpaTestcontainersTest.java
  src/test/java/com/sideteam/groupsaver/utils/context/IntegrationSpringBootTest.java
  src/test/java/com/sideteam/groupsaver/utils/provider/ClubProvider.java
Labels: Fix

#73 마이페이지 모임 카테고리 반환값 분리 및 시간 관련 포멧 통일
  .gitignore
  src/main/java/com/sideteam/groupsaver/domain/member/dto/response/MyProfileResponse.java
  src/main/java/com/sideteam/groupsaver/domain/member/repository/MemberRepositoryCustomImpl.java
  src/main/java/com/sideteam/groupsaver/global/config/ObjectMapperConfig.java
  src/test/java/com/sideteam/groupsaver/domain/member/repository/MemberRepositoryTest.java
Labels: Fix

#78 탈퇴시 회원정보 삭제
  src/main/java/com/sideteam/groupsaver/domain/member/domain/Member.java
  src/main/java/com/sideteam/groupsaver/domain/member/domain/MemberActive.java
  src/main/java/com/sideteam/groupsaver/domain/member/service/MemberUpdateService.java
Labels: Refactor

#35 Feat[#33] : QnA CRUD 개발
  src/main/java/com/sideteam/groupsaver/domain/qna/controller/QnaController.java
  src/main/java/com/sideteam/groupsaver/domain/qna/domain/Qna.java
  src/main/java/com/sideteam/groupsaver/domain/qna/dto/request/QnaRequestDto.java
  src/main/java/com/sideteam/groupsaver/domain/qna/dto/response/QnaResponseDto.java
  src/main/java/com/sideteam/groupsaver/domain/qna/repository/QnaRepository.java
  src/main/java/com/sideteam/groupsaver/domain/qna/service/QnaService.java
  src/main/java/com/sideteam/groupsaver/domain/qna_reply/controller/QnaReplyController.java
  src/main/java/com/sideteam/groupsaver/domain/qna_reply/domain/QnaReply.java
  src/main/java/com/sideteam/groupsaver/domain/qna_reply/dto/request/QnaReplyRequestDto.java
  src/main/java/com/sideteam/groupsaver/domain/qna_reply/dto/response/QnaReplyResponseDto.java
  src/main/java/com/sideteam/groupsaver/domain/qna_reply/repository/QnaReplyRepository.java
  src/main/java/com/sideteam/groupsaver/domain/qna_reply/service/QnaReplyService.java
Labels: Feat
